Code cleanup

diff --git a/Generic_Dragon01_Setup b/Generic_Dragon01_Setup
--- a/Generic_Dragon01_Setup
+++ b/Generic_Dragon01_Setup
@@ -1,37 +1,40 @@
 #!/bin/bash
 # A generic setup script for Dragon01
-# Version 1.0
+# Version 2.0
 
-if [[ $EUID -ne 0 ]]; then
-   	echo "This script must be run as root type: sudo ./Generic_Dragon01_Setup" 
-   	exit 1
-else
+    #Updating Sudoers File to Add NOPASSWD to User
+    echo "Sudo password is required for certain commands in this script."
+    echo "Entering an incorrect password will cause the script to crash."
+    read -r -s -p "Enter password: " SUDOPWD && printf "\n"
+    echo "$SUDOPWD" | sudo -S sh -c "echo \"$USER ALL=(ALL) NOPASSWD: ALL\" >&- > /etc/sudoers.d/90-$USER"
+
+
 	#Download needed files
-	echo "Downloading needed files"
-	cd /tmp || return
-	wget https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragon01_hosts
+    echo "Downloading needed files"
+    cd /tmp || return
+    wget https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragon01_hosts
 
 	#Update su permissions
-	echo "Updating sudoers file"
-	echo "david ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
+    echo "Updating sudoers file"
+    echo "david ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
 
 	#Update hosts file
-	echo "Updating the hosts file"
+    echo "Updating the hosts file"
     sudo hostnamectl set-hostname Dragon01
-	sudo cp -f ./Dragon01_hosts /etc/hosts
+    sudo cp -f ./Dragon01_hosts /etc/hosts
 
 	#Create mount points
-	echo "Creating needed mount points"
-	mkdir /home/david/.home
-	sudo mkdir /Backup
-	sudo mkdir /StorageBunker
+    echo "Creating needed mount points"
+    mkdir /home/david/.home
+    sudo mkdir /Backup
+    sudo mkdir /StorageBunker
 
 	#Core Operations
-	HOMEPART=/home/david/.home
+    HOMEPART=/home/david/.home
     HOMEDATA=/dev/nvme0n1p1
     HOMEFSTAB=$( blkid -s TYPE -o value "$HOMEDATA" )
     HOMEUUID=$( blkid -s UUID -o value "$HOMEDATA" )
-    
+
     BACKUPDATA=$( blkid -L Backup )
     BACKUPFSTAB=$( blkid -s TYPE -o value "$BACKUPDATA" )
     BACKUPUUID=$( blkid -s UUID -o value "$BACKUPDATA" )
@@ -51,136 +54,109 @@ else
     sudo mount $HOMEDATA $HOMEPART
 
     #Remove original folders and set symbolic links
-    if [ -d "$HOMEPART/Camera" ]
-    then
-        if [ -d "/home/david/Camera" ]; then sudo rm -Rf "/home/david/Camera"; fi
-        sudo ln -s "$HOMEPART/Camera" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Documents" ]
-    then
-        if [ -d "/home/david/Documents" ]; then sudo rm -Rf "/home/david/Documents"; fi
-        sudo ln -s "$HOMEPART/Documents" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Downloads" ]
-    then
-        if [ -d "/home/david/Downloads" ]; then sudo rm -Rf "/home/david/Downloads"; fi
-        sudo ln -s "$HOMEPART/Downloads" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Etcher" ]
-    then
-        if [ -d "/home/david/Etcher" ]; then sudo rm -Rf "/home/david/Etcher"; fi
-        sudo ln -s "$HOMEPART/Etcher" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Games" ]
-    then
-        if [ -d "/home/david/Games" ]; then sudo rm -Rf "/home/david/Games"; fi
-        sudo ln -s "$HOMEPART/Games" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Github" ]
-    then
-        if [ -d "/home/david/Github" ]; then sudo rm -Rf "/home/david/Github"; fi
-        sudo ln -s "$HOMEPART/Github" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Google_Drive" ]
-    then
-        if [ -d "/home/david/Google_Drive" ]; then sudo rm -Rf "/home/david/Google_Drive"; fi
-        sudo ln -s "$HOMEPART/Google_Drive" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Links" ]
-    then
-        if [ -d "/home/david/Links" ]; then sudo rm -Rf "/home/david/Links"; fi
-        sudo ln -s "$HOMEPART/Links" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Music" ]
-    then
-        if [ -d "/home/david/Music" ]; then sudo rm -Rf "/home/david/Music"; fi
-        sudo ln -s "$HOMEPART/Music" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Pictures" ]
-    then
-        if [ -d "/home/david/Pictures" ]; then sudo rm -Rf "/home/david/Pictures"; fi
-        sudo ln -s "$HOMEPART/Pictures" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Scripts" ]
-    then
-        if [ -d "/home/david/Scripts" ]; then sudo rm -Rf "/home/david/Scripts"; fi
-        sudo ln -s "$HOMEPART/Scripts" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Sync" ]
-    then
-        if [ -d "/home/david/Sync" ]; then sudo rm -Rf "/home/david/Sync"; fi
-        sudo ln -s "$HOMEPART/Sync" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Videos" ]
-    then
-        if [ -d "/home/david/Videos" ]; then sudo rm -Rf "/home/david/Videos"; fi
-        sudo ln -s "$HOMEPART/Videos" "/home/david"
-    fi
-    if [ -d "$HOMEPART/VPNac" ]
-    then
-        if [ -d "/home/david/VPNac" ]; then sudo rm -Rf "/home/david/VPNac"; fi
-        sudo ln -s "$HOMEPART/VPNac" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Wallpapers" ]
-    then
-        if [ -d "/home/david/Wallpapers" ]; then sudo rm -Rf "/home/david/Wallpapers"; fi
-        sudo ln -s "$HOMEPART/Wallpapers" "/home/david"
-    fi
-    if [ -d "$HOMEPART/Working" ]
-    then
-        if [ -d "/home/david/Working" ]; then sudo rm -Rf "/home/david/Working"; fi
-        sudo ln -s "$HOMEPART/Working" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.gnupg" ]
-    then
-        if [ -d "/home/david/.gnupg" ]; then sudo rm -Rf "/home/david/.gnupg"; fi
-        sudo ln -s "$HOMEPART/.gnupg" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.gdfuse" ]
-    then
-        if [ -d "/home/david/.gdfuse" ]; then sudo rm -Rf "/home/david/.gdfuse"; fi
-        sudo ln -s "$HOMEPART/.gdfuse" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.mozilla" ]
-    then
-        if [ -d "/home/david/.mozilla" ]; then sudo rm -Rf "/home/david/.mozilla"; fi
-        sudo ln -s "$HOMEPART/.mozilla" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.ssh" ]
-    then
-        if [ -d "/home/david/.ssh" ]; then sudo rm -Rf "/home/david/.ssh"; fi
-        sudo ln -s "$HOMEPART/.ssh" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.steam" ]
-    then
-        if [ -d "/home/david/.steam" ]; then sudo rm -Rf "/home/david/.steam"; fi
-        sudo ln -s "$HOMEPART/.steam" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.thunderbird" ]
-    then
-        if [ -d "/home/david/.thunderbird" ]; then sudo rm -Rf "/home/david/.thunderbird"; fi
-        sudo ln -s "$HOMEPART/.thunderbird" "/home/david"
-    fi
-    if [ -d "$HOMEPART/.zoom" ]
-    then
-        if [ -d "/home/david/.zoom" ]; then sudo rm -Rf "/home/david/.zoom"; fi
-        sudo ln -s "$HOMEPART/.zoom" "/home/david"
-    fi
-    if [ -f "$HOMEPART/.pam-gnupg" ]
-    then
-        if [ -f "/home/david/.pam-gnupg" ]; then sudo rm -f "/home/david/.pam-gnupg"; fi
-        sudo ln -s "$HOMEPART/.pam-gnupg" "/home/david"
-    fi
+        if [ -d "$HOMEPART/Camera" ]; then
+            if [ -d "/home/david/Camera" ]; then sudo rm -Rf "/home/david/Camera"; fi
+            sudo ln -s "$HOMEPART/Camera" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Documents" ]; then
+            if [ -d "/home/david/Documents" ]; then sudo rm -Rf "/home/david/Documents"; fi
+            sudo ln -s "$HOMEPART/Documents" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Downloads" ]; then
+            if [ -d "/home/david/Downloads" ]; then sudo rm -Rf "/home/david/Downloads"; fi
+            sudo ln -s "$HOMEPART/Downloads" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Etcher" ]; then
+            if [ -d "/home/david/Etcher" ]; then sudo rm -Rf "/home/david/Etcher"; fi
+            sudo ln -s "$HOMEPART/Etcher" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Games" ]; then
+            if [ -d "/home/david/Games" ]; then sudo rm -Rf "/home/david/Games"; fi
+            sudo ln -s "$HOMEPART/Games" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Github" ]; then
+            if [ -d "/home/david/Github" ]; then sudo rm -Rf "/home/david/Github"; fi
+            sudo ln -s "$HOMEPART/Github" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Google_Drive" ]; then
+            if [ -d "/home/david/Google_Drive" ]; then sudo rm -Rf "/home/david/Google_Drive"; fi
+            sudo ln -s "$HOMEPART/Google_Drive" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Links" ]; then
+            if [ -d "/home/david/Links" ]; then sudo rm -Rf "/home/david/Links"; fi
+            sudo ln -s "$HOMEPART/Links" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Music" ]; then
+            if [ -d "/home/david/Music" ]; then sudo rm -Rf "/home/david/Music"; fi
+            sudo ln -s "$HOMEPART/Music" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Pictures" ]; then
+            if [ -d "/home/david/Pictures" ]; then sudo rm -Rf "/home/david/Pictures"; fi
+            sudo ln -s "$HOMEPART/Pictures" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Scripts" ]; then
+            if [ -d "/home/david/Scripts" ]; then sudo rm -Rf "/home/david/Scripts"; fi
+            sudo ln -s "$HOMEPART/Scripts" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Sync" ]; then
+            if [ -d "/home/david/Sync" ]; then sudo rm -Rf "/home/david/Sync"; fi
+            sudo ln -s "$HOMEPART/Sync" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Videos" ]; then
+            if [ -d "/home/david/Videos" ]; then sudo rm -Rf "/home/david/Videos"; fi
+            sudo ln -s "$HOMEPART/Videos" "/home/david"
+        fi
+        if [ -d "$HOMEPART/VPNac" ]; then
+            if [ -d "/home/david/VPNac" ]; then sudo rm -Rf "/home/david/VPNac"; fi
+            sudo ln -s "$HOMEPART/VPNac" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Wallpapers" ]; then
+            if [ -d "/home/david/Wallpapers" ]; then sudo rm -Rf "/home/david/Wallpapers"; fi
+            sudo ln -s "$HOMEPART/Wallpapers" "/home/david"
+        fi
+        if [ -d "$HOMEPART/Working" ]; then
+            if [ -d "/home/david/Working" ]; then sudo rm -Rf "/home/david/Working"; fi
+            sudo ln -s "$HOMEPART/Working" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.gnupg" ]; then
+            if [ -d "/home/david/.gnupg" ]; then sudo rm -Rf "/home/david/.gnupg"; fi
+            sudo ln -s "$HOMEPART/.gnupg" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.gdfuse" ]; then
+            if [ -d "/home/david/.gdfuse" ]; then sudo rm -Rf "/home/david/.gdfuse"; fi
+            sudo ln -s "$HOMEPART/.gdfuse" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.mozilla" ]; then
+            if [ -d "/home/david/.mozilla" ]; then sudo rm -Rf "/home/david/.mozilla"; fi
+            sudo ln -s "$HOMEPART/.mozilla" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.ssh" ]; then
+            if [ -d "/home/david/.ssh" ]; then sudo rm -Rf "/home/david/.ssh"; fi
+            sudo ln -s "$HOMEPART/.ssh" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.steam" ]; then
+            if [ -d "/home/david/.steam" ]; then sudo rm -Rf "/home/david/.steam"; fi
+            sudo ln -s "$HOMEPART/.steam" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.thunderbird" ]; then
+            if [ -d "/home/david/.thunderbird" ]; then sudo rm -Rf "/home/david/.thunderbird"; fi
+            sudo ln -s "$HOMEPART/.thunderbird" "/home/david"
+        fi
+        if [ -d "$HOMEPART/.zoom" ]; then
+            if [ -d "/home/david/.zoom" ]; then sudo rm -Rf "/home/david/.zoom"; fi
+            sudo ln -s "$HOMEPART/.zoom" "/home/david"
+        fi
+        if [ -f "$HOMEPART/.pam-gnupg" ]; then
+            if [ -f "/home/david/.pam-gnupg" ]; then sudo rm -f "/home/david/.pam-gnupg"; fi
+            sudo ln -s "$HOMEPART/.pam-gnupg" "/home/david"
+        fi
 
     #Add ssh key
     eval "$(ssh-agent -s)"
     ssh-add /home/david/.ssh/id_rsa
-    
+
 	#Cleanup
-	echo "Cleaning up"
-	sudo rm ./Dragon01_hosts
+    echo "Cleaning up"
+    sudo rm ./Dragon01_hosts
 
-	echo "DON'T FORGET TO REBOOT!"
-
-fi
-
+    echo "DON'T FORGET TO REBOOT!"
